services:
  app:
    build: .
    ports:
      - "8080:8090"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: soap@123
      DB_NAME: cicd
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: soap@123
      MYSQL_DATABASE: cicd
    ports:
      - "3307:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
